flows:
  - type: playground
    id: Purchase_Finance_Single_Redirection_With_AA
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_With_AA.yaml
  - type: playground
    id: Purchase_Finance_Single_Redirection_Without_AA
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - SINGLE_REDIRECTION
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_Without_AA.yaml
  - type: playground
    id: Purchase_Finance_Single_Redirection_Without_AA_Cancellation
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - SINGLE_REDIRECTION
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_Without_AA_Cancellation.yaml
  - type: playground
    id: Purchase_Finance_Single_Redirection_Without_AA_Loan_Foreclosure
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - SINGLE_REDIRECTION
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_Without_AA_Loan_Foreclosure.yaml
  - type: playground
    id: Purchase_Finance_Single_Redirection_Without_AA_Missed_EMI_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - SINGLE_REDIRECTION
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_Without_AA_Missed_EMI_Payment.yaml
  - type: playground
    id: Purchase_Finance_Single_Redirection_Without_AA_Pre_Part_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - SINGLE_REDIRECTION
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Single_Redirection_Without_AA_Pre_Part_Payment.yaml
  - type: playground
    id: Purchase_Finance_With_AA
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA.yaml
  - type: playground
    id: Purchase_Finance_With_AA_Cancellation
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA_Cancellation.yaml
  - type: playground
    id: Purchase_Finance_With_AA_Loan_Foreclosure
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA_Loan_Foreclosure.yaml
  - type: playground
    id: Purchase_Finance_With_AA_Missed_EMI_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA_Missed_EMI_Payment.yaml
  - type: playground
    id: Purchase_Finance_With_AA_Multiple_Offer
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA_Multiple_Offer.yaml
  - type: playground
    id: Purchase_Finance_With_AA_Pre_Part_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITH_AA
      - REPORTABLE
    description: Purchase Finance with Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_With_AA_Pre_Part_Payment.yaml
  - type: playground
    id: Purchase_Finance_Without_AA
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA.yaml
  - type: playground
    id: Purchase_Finance_Without_AA_Cancellation
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA_Cancellation.yaml
  - type: playground
    id: Purchase_Finance_Without_AA_Loan_Foreclosure
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA_Loan_Foreclosure.yaml
  - type: playground
    id: Purchase_Finance_Without_AA_Missed_EMI_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA_Missed_EMI_Payment.yaml
  - type: playground
    id: Purchase_Finance_Without_AA_Multiple_Offer
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA_Multiple_Offer.yaml
  - type: playground
    id: Purchase_Finance_Without_AA_Pre_Part_Payment
    usecase: PURCHASE FINANCE
    tags:
      - WORKBENCH
      - WITHOUT_AA
      - REPORTABLE
    description: Purchase Finance without Account Aggregator
    config:
      $ref: src/config/FIS12/V-2.2.1/purchaseFinance/flows/Purchase_Finance_Without_AA_Pre_Part_Payment.yaml
