flows:
  - type: playground
    id: Gold_Loan_With_Account_Aggregator
    meta:
      order: 0
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan with Account Aggregator - Selection and approval flow
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_With_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Without_Account_Aggregator
    meta:
      order: 1
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan without Account Aggregator - Selection and approval flow
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Without_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Foreclosure_Without_Account_Aggregator
    meta:
      order: 2
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Loan Foreclosure (Without Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Foreclosure_Without_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Foreclosure_With_Account_Aggregator
    meta:
      order: 3
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Loan Foreclosure (With Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Foreclosure_With_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Missed_EMI_Without_Account_Aggregator
    meta:
      order: 4
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Missed EMI Payment (Without Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Missed_EMI_Without_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Missed_EMI_With_Account_Aggregator
    meta:
      order: 5
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Missed EMI Payment (With Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Missed_EMI_With_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Pre_Part_Payment_With_Account_Aggregator
    meta:
      order: 6
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Pre-Part Payment (With Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Pre_Part_Payment_With_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_Pre_Part_Payment_Without_Account_Aggregator
    meta:
      order: 7
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan - Pre-Part Payment (Without Account Aggregator)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Pre_Part_Payment_Without_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_With_Multiple_offers_With_Account_Aggregator
    meta:
      order: 8
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan with Multiple Offers (Bureau Consent & AA)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_With_Multiple_offers_With_Account_Aggregator.yaml"

  - type: playground
    id: Gold_Loan_With_Account_Aggregator_With_IGM_v-1_0_0_
    meta:
      order: 9
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan with Account Aggregator - With IGM (v1.0.0)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_With_Account_Aggregator_With_IGM_v-1_0_0_.yaml"

  - type: playground
    id: Gold_Loan_Without_Account_Aggregator_With_IGM_v-1_0_0_
    meta:
      order: 10
    usecase: GOLD_LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Gold Loan without Account Aggregator - With IGM (v1.0.0)
    config:
      $ref: "src/config/FIS12/V-2.0.2/goldLoan/flows/Gold_Loan_Without_Account_Aggregator_With_IGM_v-1_0_0_.yaml"